name: Print Text Workflow

on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Text to print'
        required: true
        default: '[{"sourceType": "gitHttps","path": "github.com/macaco","private": true,"app": "monkey","token": "ape"},{"sourceType": "terraformRegistry","path": "hashicorp","private": false}]'

jobs:
  print_text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Text
        uses: docker://rmnobarra/print-text
        with:
          text: ${{ github.event.inputs.text }}

      - name: Print Text 2
        env:
          TEXT: ${{ github.event.inputs.text }}
        run: docker run --rm -e MY_TEXT="$text" rmnobarra/print-text
        shell: bash